FROM node:alpine as build-deps
ARG REACT_APP_GOOGLE_OAUTH_CLIENTID
ENV REACT_APP_GOOGLE_OAUTH_CLIENTID=265467486812-n9nmdcuf52s0321h854tl4dg7fksjrog.apps.googleusercontent.com
RUN echo $REACT_APP_GOOGLE_OAUTH_CLIENTID
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]