version: "3.7"

services:
  smt-dev:
    container_name: sprint_summary_tool_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: .env.local
