version: "3.7"

services:
  couchdb-server:
    image: couchdb:3.1.1
    container_name: couchdb-server
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=pass12345
    volumes:
      - couchdb-data:/opt/couchdb/data
    networks:
      - couchdb_network
    ports:
      - 5984:5984
    restart: unless-stopped

  smt-dev:
    container_name: sprint_summary_tool_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on:
      - couchdb-server
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: .env.local

volumes:
  couchdb-data:
    name: couchdb-data
networks:
  couchdb_network:
    name: couchdb_network
