export const TEAM_ADD_MEMBER = "TEAM_ADD_MEMBER";
export const TEAM_REMOVE_MEMBER = "TEAM_REMOVE_MEMBER";

export const SPRINT_ADD = "SPRINT_ADD";
export const SPRINT_ADD_MEMBERS = "SPRINT_ADD_MEMBERS";
export const SPRINT_ADD_PROJECTS = "SPRINT_ADD_PROJECTS";
export const SPRINT_ADD_CAPACITY = "SPRINT_ADD_CAPACITY";
export const SPRINT_ADD_STORY_DATA = "SPRINT_ADD_STORY_DATA";
export const SPRINT_REMOVE_CAPACITY = "SPRINT_REMOVE_CAPACITY";

export const PROJECT_ADD = "PROJECT_ADD";

export const STATE_UPDATE_SELECTED_SPRINT = "STATE_UPDATE_SELECTED_SPRINT";
