export const TEAM_ADD_MEMBER = "TEAM_ADD_MEMBER";
export const TEAM_REMOVE_MEMBER = "TEAM_REMOVE_MEMBER";

export const SPRINT_ADD = "SPRINT_ADD";
export const SPRINT_ADD_MEMBERS = "SPRINT_ADD_MEMBERS";
