export const NON_PROJECT = "NON_PROJECT_MEETING";
export const NON_PROJECT_ONCALL = "NON_PROJECT_ONCALL";
export const NON_PROJECT_INTERVIEW = "NON_PROJECT_INTERVIEW";
export const NON_PROJECT_MEETING = "NON_PROJECT_MEETING";

export const NON_PROJECT_TEAM = "NON_PROJECT_TEAM";
export const PROJECT_BUSINESS = "PROJECT_BUSINESS";
