apiVersion: apps/v1
kind: Deployment
metadata:
  name: teams-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teams
  template:
    metadata:
      labels:
        app: teams
    spec:
      containers:
        - name: teams
          image: delwinrbest/smt_teams
          env:
            - name: MONGO_URI
              value: 'mongodb://teams-mongo-srv:27017/teams'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: sprintstool
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          # resources:
          #   limits:
          #     memory: '128Mi'
          #     cpu: '200m'
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/teams/healthz
              port: 3000
              httpHeaders:
                - name: Content-Type
                  value: application/json
            initialDelaySeconds: 30
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: teams-srv
spec:
  selector:
    app: teams
  ports:
    - name: teams
      protocol: TCP
      port: 3000
      targetPort: 3000
