name: deploy-sprints

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
    paths:
      - 'sprints/**'
  pull_request:
    branches: [master]
    paths:
      - 'sprints/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  AWS_DEFAULT_REGION: ap-northeast-1
  K8S_CLUSER_NAME: sprint-planning-tool

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build Container Image
        run: cd sprints && docker build -t delwinrbest/smt_sprints .

      - name: Push Image to Docker Hub
        run: docker push delwinrbest/smt_sprints
      # - name: Login doctl with Digital Ocean
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      # - name: Create kubectl Context
      #   run: doctl kubernetes cluster kubeconfig save ticketing-cluster

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Create kubectl Context
        # run: doctl kubernetes cluster kubeconfig save ticketing-cluster
        run: aws eks update-kubeconfig --region ${{ env.AWS_DEFAULT_REGION }} --name ${{ env.K8S_CLUSER_NAME }}

      - name: Init Deployment
        run: kubectl rollout restart deployment sprints-depl
