name: deploy-manifests

on:
  pull_request:
    branches:
      - master
    paths:
      - 'infra/**'

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  K8S_CLUSER_NAME: sprint-planning-tool

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Authentic doctl with Digital Ocean
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Create kubectl Context
        # run: doctl kubernetes cluster kubeconfig save ticketing-cluster
        run: aws eks update-kubeconfig --region ${{ env.AWS_DEFAULT_REGION }} --name ${{ env.K8S_CLUSER_NAME }}
      - name: Init Infra Update
        run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
