name: tests-sprints

on:
  pull_request:
    # paths:
    #   - 'sprints/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: cd sprints && npm install && npm run test:ci
