name: tests-users

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [master]
  #   paths:
  #     - 'users/**'
  pull_request:
    branches: [master]
    paths:
      - 'sprints/**'
      - 'users/**'
      - 'teams/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: cd users && npm install && npm run test:ci
