name: tests-users

on:
  pull_request:
    paths:
      - 'users/**'
  push:
    paths:
      - 'users/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd users && npm install && npm run test:ci
