name: tests-sprints

on:
  pull_request:
    paths:
      - 'sprints/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd sprints && npm install && npm run test:ci
