name: tests-teams

on:
  pull_request:
    paths:
      - 'teams/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: cd sprints && npm install && npm run test:ci
