name: tests-teams

on:
  push:
    branches:
      - master
    paths:
      - 'teams/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd teams && npm install && npm run test:ci
